# Numerical Python (numpy): arreglos


## Introducción

El paquete NumPy (por NUMerical PYthon) provee acceso a una estructura de datos llamada `array` (arreglo), que permite:

- operaciones eficientes de manejo de matrices y vectores y
- herramientas de álgebra lineal, como por ejemplo resolución de sistemas de ecuaciones, cálculo de valores y vectores propios, etc.


### Historia

Hay dos implementaciones que entegan aproximadamente la misma funcionalidad que NumPy. Esta son "Numeric" y "numarray":

- Numeric fue el primer módulo que incluía en Python un conjunto de métodos numéricos (similares a Matlab). Evolucionó a partir de una tesis doctoral. 

- Numarray es una re-implementación de Numeric con ciertas mejoras (pero para nuestros propósitos Numeric y Numarray se comportan de manera virtualmente idéntica)

- A comienzos de 2006 se decidió combinar los mejores espectos de Numeric y Numarray en el paquete `scipy` (Scientific Python) y entregar el tipo de datos `array` en el módulo `NumPy`



## Arreglos
Introducimos un nuevo tipo de datos, llamado `array`. Un arreglo se parece mucho a una lista, con la diferencia que un arreglo solo puede guardar elementos de un mismo tipo (mientras que en una lista podemos mezclar diferentes tipos de objetos). Esto implica que los arreglos se almacenan de manera más eficiente, porque no está la necesidad de guardar en cada elemento el tipo de datos. Esto también los hace el tipo de datos ideal para cálculo numérico, donde a menudo hay que lidiar con matrices y vectores. 

Los vectores y matrices (dos o más índices) se llaman *arreglos* en NumPy.


### Vectores (arreglos unidimensionales)

La estructura de datos que necesitaremos con más frecuencia son los vectores. A continuación veremos como crearlos, operar con ellos y cuáles son sus ventajas.

#### Creación y acceso a vectores:

Hay varias formas de crear vectores. 

-   Transformación de una lista (o tupla) en un arreglo usando <span>`numpy.array`</span>:

``` python
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

lista=[1,2,3,4,5]
x = np.array(lista)
print(type(x))


<class 'numpy.ndarray'>


-   Transformación de una lista (o tupla) en un arreglo usando <span>`numpy.asarray`</span>:
``` python
numpy.asarray(a, dtype=None, order=None, *, like=None)
```

In [9]:
x = np.asarray([0, 0.5, 1, 1.5])
print(x)


[0.  0.5 1.  1.5]


Diferencia entre <span>`numpy.array`</span> y <span>`numpy.asarray`</span>: 

`np.array` copia los valores (por defecto), mientras que `np.asarray` no lo hace. Además al usar `np.asarray` se puede especificar un orden (por filas, columnas, etc.).

In [10]:
a=np.asarray([1,2,3])

b=np.asarray(a)
b is a

True

In [12]:
a=np.array([1,2,3])
b=np.array(a)
b is a

False

-   Creación de un vector usando `arange` (por "ArrayRANGE”):

In [13]:
x = np.arange(0, 2, 0.5)
print(x)

[0.  0.5 1.  1.5]


- Usando los métodos `zeros` y `ones`

``` python
numpy.zeros(shape, dtype=float, order='C', *, like=None)

```

In [14]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Recuperar valores de un vector

Una vez que el arrego está definido, podemos definir y recoperar valores individuales igual que con una lista. Por ejemplo:

In [16]:
x = np.array([0,0.5,1,1.5,2,2.5])


In [17]:
x[0] = -1
x[2] = 4
print(x)
print(x[0])
print(x[0:-1])

[-1.   0.5  4.   1.5  2.   2.5]
-1.0
[-1.   0.5  4.   1.5  2. ]


Pero a diferencia de las listas, podemos recuperar una lista (o arreglo) desde cualquier índice: 

In [18]:
x[[0,2,4]]

array([-1.,  4.,  2.])

In [19]:
x[np.array([0,2,4])]


array([-1.,  4.,  2.])

No necesariamente respetando el orden:

In [20]:
x[[0,4,2]]

array([-1.,  2.,  4.])

e incluso se pueden repetir índices:

In [21]:
x[[1,1,1,0,2,1,1]]

array([ 0.5,  0.5,  0.5, -1. ,  4. ,  0.5,  0.5])

También podemos escoger elementos con una lista (o arreglo) de valores Booleanos del mismo largo:

In [24]:
print(x)
x[[True,False,True,False,True,False]]

[-1.   0.5  4.   1.5  2.   2.5]


array([-1.,  4.,  2.])

#### Operaciones de vectores

Otra diferencia con las listas es que en un vector podemos realizar cálculos sobre todos los elementos con un solo comando: 

In [25]:
print(x)

[-1.   0.5  4.   1.5  2.   2.5]


- Sumar 10 a cada elemento:

In [26]:
print(x + 10)

[ 9.  10.5 14.  11.5 12.  12.5]


- Elevar cada elemento al cuadrado

In [27]:
print(x**2)

[ 1.    0.25 16.    2.25  4.    6.25]


- NumPy incluye las funciones de la librería `math`, que se pueden aplicar a todos los elementos de un vector:

In [28]:
print(np.sin(x))

[-0.84147098  0.47942554 -0.7568025   0.99749499  0.90929743  0.59847214]


Por lo tanto, a diferencia de las listas, cuando multiplicamos un vector por un número, multiplicamos todos sus elementos:

In [29]:
y = 5*x
print(x)
print(y)

[-1.   0.5  4.   1.5  2.   2.5]
[-5.   2.5 20.   7.5 10.  12.5]


Además, a diferencia de las listas, podemos comparar un arreglo con un número, lo que equivale a comparar elemento por elemento. Por ejemplo, si tomamos el siguiente vector:

In [30]:
x = np.array([10,15,20,25,30])
x

array([10, 15, 20, 25, 30])

entonces al comparar `x` con un número, obtenemos un arreglo de las mismas dimensiones, donde cada elemento es `True` o `False`:

In [32]:
x>20

array([False, False, False,  True,  True])

In [33]:
x == 25

array([False, False, False,  True, False])

In [36]:
vector_bool=x != 30


y esto último permite recuperar partes del arreglo de manera muy eficiente:

In [37]:
x[vector_bool]

array([10, 15, 20, 25])

In [39]:
x[x>20]

array([25, 30])

In [40]:
x[x!=30]

array([10, 15, 20, 25])

**Observación:** Se puede transformar una lista en un arreglo cambiando el tipo de dato de cada elemento usando el argumento opcional `dtype` de la función `array()`. Por ejemplo:

In [41]:
lista_num = ["1.1","1.5\n","2"]
arreglo_num = np.array(lista_num, dtype = "float")
print(arreglo_num)

[1.1 1.5 2. ]


In [45]:
lista_num = ["1\n","2\n","3"]
arreglo_num = np.array(lista_num, dtype = "int")
print(arreglo_num)

[1 2 3]


### Matrices (arreglos bidimensionales)

### Creación de arreglos bidimensionales

Hay dos modos de crear un arreglo bidimensional: 

- Transformando una lista de listas en un arreglo:

In [46]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

-   Usando el método `zeros` o `ones` (por ejemplo para crear una matriz con 5 filas y 4 columnas):

``` python
numpy.empty(shape, dtype=float, order='C') 
```

In [49]:
x = np.zeros((5, 4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

que se extiende fácilmente a más dimensiones

In [50]:
x = np.zeros((2, 5, 4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

- También, usando el metodo 
``` python 
numpy.empty(shape, dtype=float, order='C') 
```

In [54]:
np.empty((1,2))

array([[1.15751666e-311, 0.00000000e+000]])

Se pueden recuperar las dimensiones de una matriz con el comando `shape`:

In [58]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(x)
filas=x.shape[0]
columnas=x.shape[1]
print(filas, columnas)

[[1 2 3]
 [4 5 6]]
2 3


In [59]:
np.zeros((2,5,4)).shape

(2, 5, 4)

#### Recuperar elementos

Se puede acceder elementos individuales usando la sintaxis que usamos para las listas:

In [60]:
x[0][0]

1

o bien:

In [61]:
x[0, 0]

1

In [62]:
x[0, 1]

2

In [63]:
x[0, 2]


3

In [64]:
x[1, 0]

4

También podemos recuperar una fila de la matriz usando la sitaxis de las listas:

In [65]:
x[0]

array([1, 2, 3])

o bien

In [66]:
x[0,:]

array([1, 2, 3])

Pero a diferencia de las listas, podemos recuperar las columnas:

In [67]:
x[:, 0]


array([1, 4])

In [68]:
x[:, 1]


array([2, 5])

### Definiendo matrices a partir de vectores

La función `eye` sirve para generar una matriz identidad:

``` python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
```

In [73]:
# np.eye(5,k=0)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Podemos usar la función `diag` para crear una matriz diagonal a partir de una lista o vector:

In [74]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Con el método `.reshape` podemos transformar un vector en una matriz

In [75]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [77]:
y = x.reshape(3,2)
print(y)

[[0 1]
 [2 3]
 [4 5]]


o transformar una matriz en una de otras dimensiones pero los mismos valores:

In [79]:
y=y.reshape(6,1)

In [80]:
y

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Módulo `random`

NumPy también incorpora el módulo `random`, que permite generar números pseudoaleatorios. 
Por ejemplo, la función `randint(low=0,high)`, que genera un valor al azar entre low (por defecto 0) y high, se puede llamar apelando al módulo `random` y a `np`:

In [86]:
np.random.randint(100)

23

Del mismo modo, podemos usar el método `random()` (que genera un número al azar entre 0 y 1). 

In [82]:
np.random.random()

0.5092666293867975

Pero además, al incluirlas con el módulo NumPy, estas funciones permiten crear arreglos y matrices de valores aleatorios:

In [83]:
np.random.randint(100,size=10)


array([35, 54, 19, 40, 54, 89, 45, 62, 18, 18])

In [87]:
np.random.randint(0,100,(10,5))

array([[61, 96, 11, 80, 69],
       [79, 51, 37, 57, 51],
       [80, 71, 77,  6, 28],
       [83, 34, 33,  3, 11],
       [14, 31, 35, 52, 13],
       [68, 79, 77, 74,  2],
       [76, 88, 75, 96, 65],
       [ 6,  0, 83, 53, 43],
       [45, 82, 56, 52, 16],
       [86,  4, 85, 24, 40]])

In [88]:
np.random.randint(100,size=(3,3))


array([[64, 23, 12],
       [54, 61, 73],
       [91, 30, 85]])

In [89]:
np.random.random(size=(3,3))


array([[0.12305701, 0.99329572, 0.34719696],
       [0.50736873, 0.5840149 , 0.55021691],
       [0.48060433, 0.30970294, 0.47933132]])

Para este último caso, hay una forma un poco más abreviada:

In [90]:
np.random.rand(3,3)


array([[0.58305087, 0.6391096 , 0.2977889 ],
       [0.62442168, 0.11942933, 0.9582119 ],
       [0.76835278, 0.3011356 , 0.52502659]])

### Otras funciones utiles de numpy

- `numpy.where()`
```python
numpy.where(condition: ArrayLike or bool, [x, y])
Return elements chosen from x or y depending on condition.
```



In [93]:
lista=[1,2,3,4,5]
np.where(np.array(lista)==4)

(array([3], dtype=int64),)

In [94]:
arreglo=np.array([10,20,30,40,50])

np.where(arreglo==20,'igual a 20','distinto de 20')

array(['distinto de 20', 'igual a 20', 'distinto de 20', 'distinto de 20',
       'distinto de 20'], dtype='<U14')

In [95]:
#Segundo ejemplo
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [96]:
np.where([[True, False],[True, True]], 
          [[1, 2],[3, 4]],[[9, 8],[7, 6]])

array([[1, 8],
       [3, 4]])

También, puedo almacenar los indices de los valores que cumplen la condición en un arreglo.

In [97]:
a = np.array([12,1,8,1,9,10,1,4])

indices=np.array(np.where(a>4))
indices

array([[0, 2, 4, 5]], dtype=int64)

- ### ```numpy.count_nonzero```
Cuenta el número de valores que no son cero en el arreglo *a*
```python 

numpy.count_nonzero(a, axis=None, *, keepdims=False)
```

In [100]:
a = np.array([[0, 1, 7, 0],
              [3, 0, 2, 7]])
np.count_nonzero(a)

5

También puede contar el número de veces en que se cumple una condición

In [101]:
a==0

array([[ True, False, False,  True],
       [False,  True, False, False]])

In [104]:
np.count_nonzero(a!=0)
np.count_nonzero(a!=0)

5

# Ejemplos

En esta clase analizaremos ejemplos de aplicaciones con las herramientas que hemos trabajado.
La idea es ir avanzando desde problemas netamente de programación hasta ejemplos relacionados con los conceptos de la clase.


## Ejemplo 1

Construya una función que permita determinar si un número es primo. El uso de la operacion modulo % puede ser útil.


In [105]:
def primo(n):
    indicador=1
    for i in range(2,n):
        if n%i==0:
            indicador=0
    if indicador==1:
        print('El número es primo')
    else: 
        print('El número no es primo')   

In [111]:
primo(132)  

El número no es primo


In [114]:
# Es posible pedir al usuario que ingrese directamente un valor, sin la necesidad de tener que escribirlo en el código.
# Para esto usaremos la función input('texto')

def primo():
    n=input('Ingrese un número para saber si es primo: ')
    n=int(n)
    
    indicador=1
    for i in range(2,n):
        if n%i==0:
            indicador=0
    if indicador==1:
        print('El número es primo')
    else: 
        print('El número no es primo') 

In [116]:
primo()

Ingrese un número para saber si es primo: 6
El número no es primo


## Ejemplo 2

Construya una función que permita recorrer una matriz y buscar un valor determinado, indicando la cantidad de veces que aparece el valor, y la posición de cada aparición. Pueden ser útiles las funciones np.asarray, np.where y np.count_nonzero que permiten transformar elementos en array de mnumpy, buscar los índices en una matriz de un valor indicado y saber la cantidad de ocurrencias de un número en una matriz respectivamente.

(La semana pasada realizamos un ejercicio similar, la idea es que se den cuenta que no siempre hay que inventar la rueda, sino que existen funciones predefinidas que pueden ser útiles.)

In [ ]:
def buscamatriz(A,n):
    indices=np.array(np.where(A==n))
    veces=np.count_nonzero(A==n)
    return indices,veces

In [ ]:
A=np.array([[1,3,2,1,5],[1,1,2,5,3],[12,65,23,6,1]])
print(A)

In [ ]:
indices,veces = buscamatriz(A,1)
print(indices)
print(veces)

# Ejemplo 3

El problema del vendedor de diarios es un clásico de la decisión bajo incertidumbre, ya que permite entender los conceptos más simples en un contexto real. Los y las alumnas deberían ya manejar el ejemplo al revés y al derecho, sin embargo, sería bueno un pequeño barniz.

El vendedor de diarios, debe decidir cada mañana la cantidad de diarios que tendrá a la venta durante el día. Cada uno de estos diarios posee un costo de c pesos. Una vez puestos a la venta, existe una variable aleatoria D que representa la cantidad de diarios que son demandados durante un día (Ojo, demandados no es lo mismo que vendidos, si la demanda es 10 y solo tengo 5 diarios a la venta, entonces solo venderé 5, a la vez que si demando 3 y tengo 20 a disposición solo venderé 3). Cada diario vendido representa un ingreso de p pesos para el vendedor. 

Es posible agregar adicionales, tales como un precio de reventa, r, de los sobrantes al final del día o un costo, q, por demanda insatisfecha (diarios demandados pero no vendidos).

De esta forma, la función de recompensa está dada por:

$R(x,D)= -c\cdot x + p\cdot \min(x,D) + r\cdot \max(0,x-D) - q\cdot \max(0,D-x)$

Lo que haremos será determinar la matriz de recompensas y, bajo distintos criterios, establecer lo que conviene hacer.

Formule una función que entregue la matriz de recompensas del vendedor de diarios, sabiendo que la demanda puede ir desde 0 a K diarios.

In [ ]:
def vendedor1(K,p,c,r,q):
    # necesitamos K+1 filas y K+1 columnas, ya que las decisiones pueden ser pedir desde 0 a K 
    # diarios y las demandas son de 0 a K diarios.
    # las filas representarán las acciones (valores de x, cuántos diarios comprar) y las columnas los eventos aleatorios (valores de D)
    mr=np.empty((K+1,K+1))
    indfilas = np.arange(0,K+1)  
    for i in range(K+1):
        for j in range(K+1):
            mr[i,j]=-c*i+p*min(i,j)+r*max(0,i-j)-q*max(0,j-i)
    return mr, indfilas    

Use la función creada para obtener la matriz de recompensas del vendedor de diarios, considerando una demanda desde 0 a 9 diarios, un precio de venta de 1500, un costo de 400, un precio de reventa de 200 y un perjuicio de 100 por demanda insatisfecha. Considere que el vector de probabilidades de las demandas es el siguiente: [0.05 0.03 0.03 0.2 0.1 0.1 0.05 0.04 0.01 0.3 0.]


In [ ]:
mr,indfilas=vendedor1(9,1500,400,200,100)
print(mr)
print(len(indfilas))

In [ ]:
mr.max()

In [ ]:
np.array(np.where(mr==mr.max()))

In [ ]:
#pip install tabulate
from tabulate import tabulate
print(tabulate(mr,headers='keys',showindex='always',tablefmt="fancy_grid"))

Ahora usaremos criterios de elección para saber que decisión tomar.
Consideraremos tres criterios


- **Maximax**: elegir la mejor opción considerando el mejor escenario para cada una.

- **Maximin**: elegir la mejor opción considerando el peor escenario para cada una.

- **Valor esperado**: elegir la mejor opción considerando la recompensa esperada ($probabilidad \cdot recompensa$)

In [ ]:
# Maximax

def maximaxvendedor(mr,indfilas):
    maximos=np.empty(len(indfilas))
    for i in range(len(indfilas)):
        maximos[i]=mr[i,:].max()
    maximo=maximos.max() # El mejor del mejor escenario
    
    max1= np.asarray(np.where(mr == maximo))
    return maximo,max1

maximo,max1=maximaxvendedor(mr,indfilas)
print('La recompensa siguiendo maximax es de '+str(maximo)+' pesos')
print('Conviene pedir', end =" ")

for i in range(len(max1[0,:])):
      print(max1[0,i], end =" ")
        
print('diarios')

In [ ]:
# Maximin

def maximinvendedor(mr,indfilas):
    minimos=np.empty(len(indfilas))
    for i in range(len(indfilas)):
        minimos[i]=np.min(mr[i,:])
    print(minimos)
    minimo=np.max(minimos)
    min1=np.asarray(np.where(minimos==minimo))
    return minimo,min1

minimo,min1=maximinvendedor(mr,indfilas)
print('La recompesa siguiendo maximin es de '+str(minimo)+' pesos')
print('Conviene pedir', end =" ")
for i in range(len(min1[0,:])):
      print(min1[0,i], end =" ")

In [ ]:
# Valor esperado

def vesperadovendedor(mr,indfilas,v):
    resp=np.empty(len(indfilas))
    for i in range(len(indfilas)):
        resp[i]=np.dot(v,mr[i,:])
    mejor=np.max(resp)
    vesp1=np.asarray(np.where(resp==mejor))
    return mejor,vesp1

v=np.array([0.05, 0.035, 0.03, 0.2, 0.2, 0.15, 0.15, 0.03, 0.01, 0.1])
mejor,vesp1=vesperadovendedor(mr,indfilas,v)
print('La recompesa esperada es de '+str(mejor)+' pesos')
print('Conviene pedir', end =" ")
for i in range(len(vesp1[0,:])):
      print(vesp1[0,i], end =" ")