# Laboratorio IO: Clase 01 

Primeramente recordaremos uso básico de elementos de Python.

Como sabemos, podemos usar Python como una simple calculadora, simplemente indicando las operaciones

## Uso básico de Pyhton

In [1]:
# Suma
2+3

5

In [2]:
# Resta
2-3

-1

In [3]:
# Multiplicación
2*3

6

In [4]:
# División
2/3

0.6666666666666666

In [5]:
# Potencia
2**3

8

In [6]:
# Ademas, es posible definir variables de diferentes tipos, para esto basta asignar el valor respectivo y Python reconocerá el tipo de variable necesario


In [7]:
# Número
a=2

In [8]:
b='hola mundo'

In [9]:
# Para mostrar variables es posible usar el comando print
print(a)
print(b)

2
hola mundo


Existe también en Python la opción de poder usar condicionales a través de variables booleanas (True (1) or False (0)).

Para esto podemos definir las variables directamente o bien podemos crear condiciones a través del uso de operadores lógicos

Ocupamos tres operadores or, and y not

In [10]:
# Ejemplos operadores:
(2>3) or (2<4)

True

In [11]:
not (2<3)

False

In [12]:
(2<3) and (2<4)

True

### Condicionales

El condicional por defecto es if, el cual implica que si se cumple la condición indicada, la acción se ejecutara.
La estructura es siempre 

if condición: 

    acción
    
Note que siempre es necesario el ":" a la vez que la sangría para la acción

In [13]:
# Ejemplo de uso de if
if 2<3:
    print("2 es menor que 3, quién lo diría ¡¿no?!")

2 es menor que 3, quién lo diría ¡¿no?!


Es posible indicar una acción en caso de que no se cumpla. Para esto usamos else que posee la siguiente estructura

if condición:

    acción en caso de que se cumpla
    
else:

    acción en caso de que no se cumpla

In [14]:
# Ejemplo if else
if 2>3:
    print("Es verdadero")
else:
    print("Es falso")
        

Es falso


Es posible escribir varios if consecutivos a traves de elif, al que también se le puede añadir un else final para los casos que no fueron filtrados. La estructura es:

if condición1:

    acción en caso de que se cumpla la primera condición
    
elif condición2:  

    acción si se cumple condición 2 luego de no cumplida la primera
    
else:

    acción en caso de que no se cumpla ningúna de las condiciones

In [15]:
# Ejemplo elif
a=2
b=1.5
if a+b <= 3:
    print("es menor que 3")
elif a+b < 4:
    print("el valor está entre 3 y 4")
else:
    print("el valor de la suma es mayor o igual a 4")

el valor está entre 3 y 4


## Uso de numpy para matrices

Numpy es un paquete que permite realizar diversas operaciones con elementos matemáticos, entre ellos, las matrices.
Para usar numpy, es fundamental importarla cuando creemos un nuevo Notebook. Para esto la estructura es 

import numpy as np

En este caso no solo importamos numpy sino que además lo renombramos como np.

In [16]:
import numpy as np

In [17]:
#Creación de matrices

A = np.array([[1, 1],
              [0, 1]])
print(A)
B = np.array([[1, 1, 2],
              [0, 1, 0]])

print(B)

# Creación de matrices de ceros

C = np.zeros((2, 3))

print(C)

# Creación de matrices de unos

D = np.ones((2, 3))

print(C)

# Creación de matrices identidad

E = np.identity((3))

print(E)


[[1 1]
 [0 1]]
[[1 1 2]
 [0 1 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Suma (resta) de matrices

A = np.array([[1, 1],
              [0, 1]])

B = np.array([[3, -1],
              [0, 2]])

C=A+B
print(C)

[[4 0]
 [0 3]]


In [19]:
# Multiplicación (OJO, no sirve hacer A*B ya que esto provoca que se multipliquen los respectivos elementos y no la multiplicación matricial)

C=np.matmul(A, B)
print(C)

[[3 1]
 [0 2]]


### Matrices vacías

En múltiples ocasiones deseamos usar matrices vacías a fin de luego llenarlas con elementos a través de operatoria. Para esto usaremos el comando numpy.empty, el cual permite generar una matriz vacía. Si bien la matriz está vacía, a veces Python asigna de forma aleatoria números ya que computacionalmente es mejor hacerlo de esta forma. Estos valores solo son un display y no se usan como parte de los cálculos.

Una vez creada una matriz vacía, nos interesa llenarla con valores a través de operaciones. Para esto usamos los índices de las matrices. 

ES DE SUMA IMPORTANCIA RECORDAR QUE LOS ÍNDICES EN LAS PYTHON PARTEN DESDE EL 0 EN ADELANTE

In [20]:
# Creación de matriz vacía
A=np.empty([2, 2])

#llenado de elementos de forma individual
A[0,0]=1
A[0,1]=3
A[1,0]=-5
A[1,1]=6

print(A)



[[ 1.  3.]
 [-5.  6.]]


In [21]:
#Es posible llenar directamente toda una fila o toda una columna, o bien toda la matriz usando la siguiente composición

#Llenado de una columna
B=np.empty([3, 4])
B[:,1]=2
print(B)

[[8.43891345e-312 2.00000000e+000 0.00000000e+000 0.00000000e+000]
 [2.22809558e-312 2.00000000e+000 6.52918173e-042 7.25487150e+169]
 [1.87021880e-051 2.00000000e+000 3.05686714e-057 5.92638190e-062]]


In [22]:
#Llenado de una fila
B=np.empty([3, 4])
B[2,:]=1
print(B)


[[8.43891345e-312 2.00000000e+000 0.00000000e+000 0.00000000e+000]
 [2.22809558e-312 2.00000000e+000 6.52918173e-042 7.25487150e+169]
 [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000]]


In [23]:
#Llenado de toda la matriz
B=np.empty([3, 4])
B[:,:]=-1
print(B)

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [24]:
# Es posible conocer valores, es decir, acceder a ellos.
B=np.array([[3, 4],[2,6]])
print(B)
print(B[1,1])


[[3 4]
 [2 6]]
6
