# Ejercicio Cruz Roja

La Cruz Roja debe determinar la asignación óptima de equipos médicos a los países afectados por el brote del virus Ébola. Para lo anterior, cuenta con 5 equipos médicos los cuales debe asignar a 3 países.

Las cantidades de vidas que se salvarían, dependiendo del número de equipos médicos los cuales debe asignar a 3 países.

Las cantidades de vidas que se salvarían, dependiendo del número de equipos médicos que se asignen a cada país, se señalan en la tabla.

Encuentre la solución óptima para salvar la mayor cantidad de vidas.

\begin{table}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{|l|l|l|l|}
\hline
Equipos & País 1 & País 2 & País 3 \\ \hline
0       & 0      & 0      & 0      \\ \hline
1       & 45     & 20     & 50     \\ \hline
2       & 70     & 45     & 70     \\ \hline
3       & 90     & 75     & 80     \\ \hline
4       & 105    & 110    & 100    \\ \hline
5       & 120    & 150    & 130    \\ \hline
\end{tabular}%
}
\end{table}

Etapas: N = 3, 1 por cada país.

Variable de decisión:\
$X_{n}: \text{Cantidad de equipos médicos a asignar en el país n}$

Variable de Estado:\
$S_{n}: \text{Cantidad de equipos médicos disponibles para asignar en el país n}$

Función de Recursividad:\
$S_{n+1}=S_n-X_n$

Función Objetivo:

$\max \limits_{X_n, S_n} V_n (X_n) +F^*(S_{n+1})$

Restricciones:

$S_n \geq X_n$\
$X_n\geq 0$

Condiciones de borde:

$S_1=5$ \
$S_{N+1}=S_4=0 \rightarrow X_3=S_3 $

In [69]:
import numpy as np

In [61]:
#                0  1  2  3  4  5
vidas=np.array([[0,45,70,90,105,120],#Pais 1 #Cada fila es una etapa y cada columna un x
                [0,20,45,75,110,150],#Pais 2
                [0,50,70,80,100,130]])#Pais 3

In [75]:
s=[0,1,2,3,4,5]
x=[0,1,2,3,4,5]

etapas=[0,1,2]

In [77]:
DATA=[]
for i in reversed(etapas):
    tabla=np.zeros((len(s),len(x)+2))
    for j in range(len(s)):
        for k in range(len(x)):
            if s[j]>=x[k]:
                if i==2:#Etapa (pais) 3
                    tabla[j,k]=vidas[i,k]

                if i==1: #Etapa 2 (pais 2)
                    optimoAnterior=DATA[0][s.index((s[j]-x[k])),len(x)+1]
                    tabla[j,k]=vidas[i,k]+optimoAnterior

                if i==0: #Etapa 1 (pais 1)
                    optimoAnterior=DATA[0][s.index((s[j]-x[k])),len(x)+1]
                    tabla[j,k]=vidas[i,k]+optimoAnterior

            if tabla[j,k]>tabla[j,len(x)+1]:
                tabla[j,len(x)+1]=tabla[j,k]
                tabla[j,len(x)]=x[k]
    DATA.insert(0,tabla)

In [83]:
from tabulate import tabulate

In [85]:
for pais, tabla in zip(etapas,DATA):
    print(f'Pais {pais+1}\n',tabulate(tabla, headers='0 1 2 3 4 5 x* Fx*'.split()))


Pais 1
   0    1    2    3    4    5    x*    Fx*
---  ---  ---  ---  ---  ---  ----  -----
  0    0    0    0    0    0     0      0
 50   45    0    0    0    0     0     50
 70   95   70    0    0    0     1     95
 95  115  120   90    0    0     2    120
125  140  140  140  105    0     1    140
160  170  165  160  155  120     1    170
Pais 2
   0    1    2    3    4    5    x*    Fx*
---  ---  ---  ---  ---  ---  ----  -----
  0    0    0    0    0    0     0      0
 50   20    0    0    0    0     0     50
 70   70   45    0    0    0     0     70
 80   90   95   75    0    0     2     95
100  100  115  125  110    0     3    125
130  120  125  145  160  150     4    160
Pais 3
   0    1    2    3    4    5    x*    Fx*
---  ---  ---  ---  ---  ---  ----  -----
  0    0    0    0    0    0     0      0
  0   50    0    0    0    0     1     50
  0   50   70    0    0    0     2     70
  0   50   70   80    0    0     3     80
  0   50   70   80  100    0     4    100
  0   50  

In [72]:
lista.insert(0,10)

In [73]:
lista

[10, 1, 2, 3, 4]

In [70]:
tabla=np.zeros((len(s),len(x)+2))
tabla

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
from tabulate import tabulate

In [63]:
#for etapa, i in zip(etapas,DATA):
#    print(f'\nPaís {etapa+1}\n',tabulate(i, headers='0 1 2 3 4 5 x* Fx*'.split()))

Debido a diferentes conflictos y catástrofes internacionales, la organización de médicos sin límites (MSL) se encuentra determinando la cantidad de equipos médicos que enviará a diferentes países con el fin de poder ofrecer atención de emergencia en las zonas de alta demanda.

Para esto, la organización ha identificado T posibles países en donde enviar los equipos y de acuerdo con sus estudios, ha determinado la cantidad de personas que se podrían atender dependiendo del número de equipos que se envien. Así $C_n(x)$ corresponde a la cantidad de personas que pueden ser atendidas en el país n si se envían $x$ equipos médicos.

Actualmente MSL cuenta con un total de R equipos médicos y desea que usted les indique la forma en la que asignen esos equipos a fin de maximizar la cantidad de personas que pueden ser atendidas.

Para este problema usted ha formulado el siguiente modelo de programación dinámica, el cual se pide que programe y resuelva en Python:

**Etapas**

$T$, una por cada país.

**Variables de decisión**:

$X_n:$ cantidad de equipos médicos a enviar al país $n$

**Variables de estado**: 

$S_n:$ cantidad de equipos médicos que quedan sin enviar al inicio de la etapa $n$.

**Reglas de transformación** 

$S_{n+1}=S_n-X_n$

**Función de recursividad**

$f_n(S_n,Y_n,X_n)=C_n(X_n)+f_{n+1}^*(S_{n+1})$, para todo $n$.

**Función objetivo** 

$f_n^*(S_n)=\max_{X_n} (f_n(S_n,X_n))$ para todo $n$.

**Condiciones**

$S_1=R$

$f_4^*(S_4)=0$

**Restricciones**

$X_n \leq S_n$ para todo $n$.

$X_n, S_n \geq 0$, enteras, para todo $n$.



Es importante ante todo definir la estructura que tendrán los datos que le entregaremos al modelo.

En primer lugar necesitamos una matriz que contenga los valores de la función $C_n$, para poder establecerlos, a la vez que determinar la estructura de las etapas y sus respectivas tablas.

La información de la función $C_n$ estará dada por una matriz, que poseerá $R+1$ filas y $T$ columnas, así se posee una fila por cada asignación posible de equipos médicos (de $0$ a $R$) y una columna por cada país. De esta forma, el valor $C[i,j]:$ será la cantidad de personas que pueden ser atendidas si se asignan $i$ equipos médicos al equipo $j$.

Para las etapas usaremos un arreglo de tres dimensiones, la primera dimensión corresponderá a las distinas etapas, la segunda a los valores de la variable de estado y la tercera a los valores de la variable de decisión. Como en este caso es posible asignar cualquier cantidad de equipos médicos a un país (respetando las restricciones) las filas van de $0$ a $R$, al igual que las columnas.

Asignaremos el valor -1 para inicializar las matrices de las etapas, a fin de poder determinar aquellas celdas infactibles.

Guardaremos los valores óptimos en un arreglo de dos dimensiones. En las filas tendremos los distintos valores de equipos médicos disponibles y en las columnas las distintas etapas.

In [64]:
import numpy as np
def asignacionmedica(T,R,C): # T será la cantidad de países, R la cantidad de equipos médicos totales.
    etapas = -1*np.ones((T,R+1,R+1)) # generamos las T etapas, cada una con R filas y columnas.
    mejores = np.zeros((R+1,T+1)) # generamos la matriz para los óptimos.
    for k in range(T-1,-1,-1):
        for i in range(R+1):
            for j in range(R+1):
                if j <= i:
                    etapas[k,i,j]=C[j,k]+mejores[i-j,k+1] # calculamos el valor actual y le sumamos la parte recursiva
                    # de esta forma, calculamos la cantidad de equipos sobrantes, correspondientes a los
                    # que tenemos menos los que asignamos.
            mejores[i,k]=np.max(etapas[k,i,:]) # para cada fila, determinamos el mejor valor posible.
    return etapas,mejores

In [65]:

C = np.array([[0,0,0,0],
              [7,8,11,10],
              [18,19,15,21],
              [27,31,28,30],
              [35,37,33,38]])
print(C)

[[ 0  0  0  0]
 [ 7  8 11 10]
 [18 19 15 21]
 [27 31 28 30]
 [35 37 33 38]]


In [66]:
a,b = asignacionmedica(4,4,C)
print(a)
print(b)

[[[ 0. -1. -1. -1. -1.]
  [11.  7. -1. -1. -1.]
  [21. 18. 18. -1. -1.]
  [32. 28. 29. 27. -1.]
  [42. 39. 39. 38. 35.]]

 [[ 0. -1. -1. -1. -1.]
  [11.  8. -1. -1. -1.]
  [21. 19. 19. -1. -1.]
  [32. 29. 30. 31. -1.]
  [41. 40. 40. 42. 37.]]

 [[ 0. -1. -1. -1. -1.]
  [10. 11. -1. -1. -1.]
  [21. 21. 15. -1. -1.]
  [30. 32. 25. 28. -1.]
  [38. 41. 36. 38. 33.]]

 [[ 0. -1. -1. -1. -1.]
  [ 0. 10. -1. -1. -1.]
  [ 0. 10. 21. -1. -1.]
  [ 0. 10. 21. 30. -1.]
  [ 0. 10. 21. 30. 38.]]]
[[ 0.  0.  0.  0.  0.]
 [11. 11. 11. 10.  0.]
 [21. 21. 21. 21.  0.]
 [32. 32. 32. 30.  0.]
 [42. 42. 41. 38.  0.]]


In [67]:
# Ahora generaremos una metodología para poder determinar las decisiones a tomar.
def politicaoptima(a,mejores,S):
    decision = np.zeros(len(a))
    pacientes=mejores[S,0]
    decision[0] = np.asarray(np.where(a[0,S,:]==mejores[S,0]))
    for i in range(1,len(a)):
        S = S-decision[i-1]
        decision[i] = np.asarray(np.where(a[i,int(S),:]==mejores[int(S),i]))
    return decision,pacientes

In [68]:
policy,pacientes=politicaoptima(a,b,4)
print(policy,pacientes)

[0. 3. 1. 0.] 42.0


Notemos que no estamos considerando aquellos casos en donde la solución implica múltiples caminos. Por ahora no nos preocuparemos de estos casos, ya que implican una complejidad superior a la que vemos en este curso.